"""empty message

Revision ID: 0236e303b8c9
Revises: 611eb50d5b17
Create Date: 2025-05-09 14:42:18.893208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0236e303b8c9'
down_revision = '611eb50d5b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_data_id', sa.Integer(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_message_shared_data', 'shared_data', ['shared_data_id'], ['id'])
        batch_op.drop_column('shared_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_data', sqlite.JSON(), nullable=True))
        batch_op.drop_constraint('fk_message_shared_data', type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('shared_data_id')

    # ### end Alembic commands ###
