"""empty message

Revision ID: 285752f439a2
Revises: 0236e303b8c9
Create Date: 2025-05-12 22:38:16.154453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '285752f439a2'
down_revision = '0236e303b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_message')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_data', sa.JSON(), nullable=True))
        batch_op.drop_constraint('fk_message_shared_data', type_='foreignkey')
        batch_op.drop_column('shared_data_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_data_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_message_shared_data', 'shared_data', ['shared_data_id'], ['id'])
        batch_op.drop_column('shared_data')

    op.create_table('_alembic_tmp_message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=True),
    sa.Column('shared_data', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
