"""remove bio field from user model

Revision ID: bcc6e94649b7
Revises: 2a37cd01434a
Create Date: 2025-04-30 11:22:54.131244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc6e94649b7'
down_revision = '2a37cd01434a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
